version: '3.8'

services:
    rust:
        build:
            context: .
            dockerfile: docker/rust/Dockerfile
        tty: true
        working_dir: /workspace
        volumes:
            - .:/workspace
            - rust-target:/workspace/target
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: local_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
        # ports:
        #     - 3306:3306

volumes:
    rust-target:
    db-data:
