version: '3.8'

services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - rust-target:/workspace/target

volumes:
  rust-target:
